name: Maven Build and Test

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the master branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Install Chrome and Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install xmlstarlet
        run: |
          sudo apt-get install -y xmlstarlet

      - name: Build with Maven and generate Surefire report
        run: mvn clean verify -Dsurefire.reportName=TEST-total

      - name: List contents of target/surefire-reports
        run: |
          ls -l target/surefire-reports

      - name: Display Surefire XML report
        if: always()  # Ensure this step always runs, regardless of previous steps' outcomes
        run: |
          echo "Contents of Surefire XML report (TEST-total.xml):"
          cat target/surefire-reports/testng-results.xml || echo "Surefire XML report not found."

      - name: Extract test results
        id: extract_results
        run: |
          passed=$(xmlstarlet sel -t -v "count(//testcase[@status='passed'])" target/surefire-reports/testng-results.xmll)
          failed=$(xmlstarlet sel -t -v "count(//testcase[@status='failed'])" target/surefire-reports/testng-results.xml)
          total=$(xmlstarlet sel -t -v "count(//testcase)" target/surefire-reports/testng-results.xml)
          echo "::set-output name=passed::$passed"
          echo "::set-output name=failed::$failed"
          echo "::set-output name=total::$total"

      - name: Display test results summary
        if: always()  # Ensure this step always runs, regardless of previous steps' outcomes
        run: |
          passed=$(echo "${{ steps.extract_results.outputs.passed }}")
          failed=$(echo "${{ steps.extract_results.outputs.failed }}")
          total=$(echo "${{ steps.extract_results.outputs.total }}")
          echo "Total test cases: $total"
          echo "Passed: $passed"
          echo "Failed: $failed"

      - name: Upload Surefire XML report as artifact
        if: success()  # Only upload artifact if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports
