name: Java 17 Test on Chrome and Firefox

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on Chrome and Firefox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'  # Specify the distribution here

      - name: Install Chrome and Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Build with Maven and generate Surefire report
        run: mvn clean verify -Dsurefire.reportName=TEST-total

      - name: Parse Surefire XML report
        id: test-results
        run: |
          total_tests=$(grep -oP '(?<=<tests run=")\d+' target/surefire-reports/TEST-total.xml | tail -1)
          echo "Total number of test cases: $total_tests"
