name: orange builf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on Chrome and Firefox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Chrome and Firefox
        uses: uber-web/browser-action@v1
        with:
          browsers: 'chrome, firefox'

      - name: Build with Maven and generate Surefire report
        run: mvn clean verify -Dsurefire.reportName=TEST-total

      - name: Parse Surefire XML report
        id: test-results
        run: |
          total_tests=$(grep -oP '(?<=<tests run=")\d+' target/surefire-reports/TEST-total.xml | tail -1)
          echo "Total number of test cases: $total_tests"

      # Add more steps as necessary for your testing process
