name: Maven Build and Test

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the master branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          maven-version: '3.8.3'  # Specify the Maven version if needed

      - name: Install Firefox
        run: sudo apt-get install firefox

      - name: Install GeckoDriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux-aarch64.tar.gz
          tar -xzf geckodriver-v0.34.0-linux-aarch64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Build and Test with Maven
        run: mvn clean verify  

      - name: List contents of target/surefire-reports
        run: |
          ls -l target/surefire-reports

      - name: Display Surefire XML report
        if: always()
        run: |
          echo "Contents of Surefire XML report (testng-results.xml):"
          cat target/surefire-reports/testng-results.xml || echo "Surefire XML report not found."

      - name: Extract test results
        id: extract_results
        run: |
          total_tests=$(xmlstarlet sel -t -v "/testng-results/@total" target/surefire-reports/testng-results.xml)
          failed_tests=$(xmlstarlet sel -t -v "/testng-results/@failed" target/surefire-reports/testng-results.xml)
          skipped_tests=$(xmlstarlet sel -t -v "/testng-results/@skipped" target/surefire-reports/testng-results.xml)
          passed_tests=$(xmlstarlet sel -t -v "/testng-results/@passed" target/surefire-reports/testng-results.xml)
          echo "::set-output name=passed::$passed_tests"
          echo "::set-output name=failed::$failed_tests"
          echo "::set-output name=skipped::$skipped_tests"
          echo "::set-output name=total::$total_tests"

      - name: Display test results summary
        if: always()
        run: |
          echo "Total test cases: ${{ steps.extract_results.outputs.total }}"
          echo "Passed: ${{ steps.extract_results.outputs.passed }}"
          echo "Failed: ${{ steps.extract_results.outputs.failed }}"
          echo "Skipped: ${{ steps.extract_results.outputs.skipped }}"

      - name: Upload Surefire XML report as artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports
