name: Maven Build and Test with Xvfb

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the master branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Install Chrome, Firefox, and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y xvfb
          sudo apt-get install -y xorg
          sudo apt-get install -y dbus-x11

      - name: Install xmlstarlet
        run: |
          sudo apt-get install -y xmlstarlet

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3  # Give Xvfb some time to start

      - name: Build with Maven and generate Surefire report
        run: mvn clean verify -Dsurefire.reportName=TEST-total

      - name: List contents of target/surefire-reports
        run: |
          ls -l target/surefire-reports

      - name: Display Surefire XML report
        if: always()  # Ensure this step always runs, regardless of previous steps' outcomes
        run: |
          echo "Contents of Surefire XML report (TEST-TestSuite.xml):"
          cat target/surefire-reports/TEST-TestSuite.xml || echo "Surefire XML report not found."

      - name: Extract test results
        id: extract_results
        run: |
          ls -l target/surefire-reports  # Verify contents of surefire-reports directory
          passed=$(xmlstarlet sel -t -v "count(//testcase[@status='PASS'])" target/surefire-reports/TEST-TestSuite.xml)
          failed=$(xmlstarlet sel -t -v "count(//testcase[@status='FAIL'])" target/surefire-reports/TEST-TestSuite.xml)
          total=$(xmlstarlet sel -t -v "count(//testcase)" target/surefire-reports/TEST-TestSuite.xml)
          echo "::set-output name=passed::$passed"
          echo "::set-output name=failed::$failed"
          echo "::set-output name=total::$total"

      - name: Display test results summary
        if: always()  # Ensure this step always runs, regardless of previous steps' outcomes
        run: |
          passed=$(echo "${{ steps.extract_results.outputs.passed }}")
          failed=$(echo "${{ steps.extract_results.outputs.failed }}")
          total=$(echo "${{ steps.extract_results.outputs.total }}")
          echo "Total test cases: $total"
          echo "Passed: $passed"
          echo "Failed: $failed"

      - name: Upload Surefire XML report as artifact
        if: success()  # Only upload artifact if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports
