name: Selenium Tests with Firefox and Chrome

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          maven-version: '3.1.0'

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Pull Selenium Docker image
        run: docker pull selenium/standalone-firefox:latest

      - name: Verify Docker image
        run: docker run --rm selenium/standalone-firefox:latest firefox --version

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Display Surefire XML report
        if: always()
        run: |
          echo "Contents of Surefire XML report (testng-results.xml):"
          cat target/surefire-reports/testng-results.xml || echo "Surefire XML report not found."

      - name: Extract test results
        id: extract_results
        run: |
          total_tests=$(xmlstarlet sel -t -v "/testng-results/@total" target/surefire-reports/testng-results.xml)
          failed_tests=$(xmlstarlet sel -t -v "/testng-results/@failed" target/surefire-reports/testng-results.xml)
          passed_tests=$(xmlstarlet sel -t -v "/testng-results/@passed" target/surefire-reports/testng-results.xml)
          chrome_passed=$(xmlstarlet sel -t -v "count(//test-method[contains(@name,'chrome')][@status='PASS'])" target/surefire-reports/testng-results.xml)
          chrome_failed=$(xmlstarlet sel -t -v "count(//test-method[contains(@name,'chrome')][@status='FAIL'])" target/surefire-reports/testng-results.xml)
          firefox_passed=$(xmlstarlet sel -t -v "count(//test-method[contains(@name,'firefox')][@status='PASS'])" target/surefire-reports/testng-results.xml)
          firefox_failed=$(xmlstarlet sel -t -v "count(//test-method[contains(@name,'firefox')][@status='FAIL'])" target/surefire-reports/testng-results.xml)
          echo "::set-output name=total::$total_tests"
          echo "::set-output name=failed::$failed_tests"
          echo "::set-output name=passed::$passed_tests"
          echo "::set-output name=chrome_passed::$chrome_passed"
          echo "::set-output name=chrome_failed::$chrome_failed"
          echo "::set-output name=firefox_passed::$firefox_passed"
          echo "::set-output name=firefox_failed::$firefox_failed"

      - name: Display test results summary
        if: always()
        run: |
          echo "Total test cases = ${{ steps.extract_results.outputs.total }}"
          echo "Passed test cases = ${{ steps.extract_results.outputs.passed }}"
          echo "Failed test cases = ${{ steps.extract_results.outputs.failed }}"
          echo "------------------------------"
          echo "Chrome Test Cases:"
          echo "1- Passed test cases = ${{ steps.extract_results.outputs.chrome_passed }}"
          xmlstarlet sel -t -m "//test-method[@status='PASS' and contains(@name, 'chrome')]" -v "@name" -n target/surefire-reports/testng-results.xml || echo "No passed tests for Chrome"
          echo "2- Failed test cases = ${{ steps.extract_results.outputs.chrome_failed }}"
          xmlstarlet sel -t -m "//test-method[@status='FAIL' and contains(@name, 'chrome')]" -v "@name" -n target/surefire-reports/testng-results.xml || echo "No failed tests for Chrome"
          echo "------------------------------"
          echo "Firefox Test Cases:"
          echo "1- Passed test cases = ${{ steps.extract_results.outputs.firefox_passed }}"
          xmlstarlet sel -t -m "//test-method[@status='PASS' and contains(@name, 'firefox')]" -v "@name" -n target/surefire-reports/testng-results.xml || echo "No passed tests for Firefox"
          echo "2- Failed test cases = ${{ steps.extract_results.outputs.firefox_failed }}"
          xmlstarlet sel -t -m "//test-method[@status='FAIL' and contains(@name, 'firefox')]" -v "@name" -n target/surefire-reports/testng-results.xml || echo "No failed tests for Firefox"

      - name: Upload Surefire XML report as artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Generate Markdown table
        id: generate_markdown_table
        run: |
          echo "### Chrome Test Cases:"
          echo "1- Passed test cases = ${{ steps.extract_results.outputs.chrome_passed }}"
          xmlstarlet sel -t -m "//test-method[@status='PASS' and contains(@name, 'chrome')]" -v "@name" -n target/surefire-reports/testng-results.xml || echo "No passed tests for Chrome"
          echo "2- Failed test cases = ${{ steps.extract_results.outputs.chrome_failed }}"
          xmlstarlet sel -t -m "//test-method[@status='FAIL' and contains(@name, 'chrome')]" -v "@name" -n target/surefire-reports/testng-results.xml || echo "No failed tests for Chrome"
          echo "------------------------------"
          echo "### Firefox Test Cases:"
          echo "1- Passed test cases = ${{ steps.extract_results.outputs.firefox_passed }}"
          xmlstarlet sel -t -m "//test-method[@status='PASS' and contains(@name, 'firefox')]" -v "@name" -n target/surefire-reports/testng-results.xml || echo "No passed tests for Firefox"
          echo "2- Failed test cases = ${{ steps.extract_results.outputs.firefox_failed }}"
          xmlstarlet sel -t -m "//test-method[@status='FAIL' and contains(@name, 'firefox')]" -v "@name" -n target/surefire-reports/testng-results.xml || echo "No failed tests for Firefox"
          
      - name: Upload Markdown table as artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: markdown_table.md
