name: Maven Build and Test

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the master branch

jobs:
  build-and-test:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Set up ChromeDriver and GeckoDriver
        run: |
          choco install chromedriver
          choco install geckodriver

      - name: Run Selenium Tests
        run: mvn clean verify

      - name: Display Test Results Summary
        if: always()
        run: |
          echo "=== Test Results ==="
          cat target/surefire-reports/*.txt || echo "No test results found"
          
          total_tests=$(grep -oE 'Tests run: [0-9]+' target/surefire-reports/*.txt | grep -oE '[0-9]+')
          if [ -z "$total_tests" ]; then
            total_tests=0
          fi

          passed_tests=$(grep -oE 'Tests run: [0-9]+, Failures: [0-9]+, Errors: [0-9]+, Skipped: [0-9]+' target/surefire-reports/*.txt | grep -oE 'Failures: [0-9]+,' | grep -oE '[0-9]+')
          if [ -z "$passed_tests" ]; then
            passed_tests=0
          fi

          failed_tests=$(grep -oE 'Tests run: [0-9]+, Failures: [0-9]+, Errors: [0-9]+, Skipped: [0-9]+' target/surefire-reports/*.txt | grep -oE 'Errors: [0-9]+,' | grep -oE '[0-9]+')
          if [ -z "$failed_tests" ]; then
            failed_tests=0
          fi

          echo "Total Test Cases: $total_tests"
          echo "Passed Test Cases: $passed_tests"
          echo "Failed Test Cases: $failed_tests"
